### PR TITLE
GCM credentials renamed to FCM credentials. Facebook messenger appId …

### PR DESCRIPTION
**Pull request by tmihnovits**
…and pageId changed from static values to placeholders

### CODE REVIEW

**Comment by kwhinnery** [comment]
@jefflinwood ?

**Comment by jefflinwood** [comment]
We don't need the GCM or FCM credentials anymore - can we just merge the Facebook changes?

**Comment by viktormuller** [comment]
If we have the GCM Credential stuff already removed then imho it's ok to just merge the Facebook changes. 

@jefflinwood Do you need anything from us to merge just those? (i am not great with cherry picking in Git).

**Comment by jefflinwood** [comment]
@viktormuller - No I can take out the relevant pieces and then merge them in as a new PR

**Comment by coderkat-zz** [comment]
Closing this and re-opening a PR that just removes GCM credential and does the FB id updates: https://github.com/TwilioDevEd/notifications-quickstart-node/pull/10

**Comment by viktormuller** [comment]
Great +1

**Pull request closed without merging**
